generatorName: java
outputDir: samples/client/petstore/java/aws-java-client
library: aws-java-client
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-aws-java-client
  hideGenerationTimestamp: "true"
